# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220)),
                ('shortcode', models.CharField(blank=True, max_length=15, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('clicked_times', models.IntegerField(default=0)),
            ],
        ),
    ]
